### ISSUE TITLE
gpt Table.GetPartitionSize() returning incorrect size

### ISSUE THREAD

**Issue by queuem** [diskfs/go-diskfs#10]
The Size field in gpt.Partition is in bytes, but gpt.Table.GetPartitionSize() is multiplying the  gpt.Partition.Size by the sector size (see https://github.com/diskfs/go-diskfs/blob/master/partition/mbr/table.go#L181)

This caused disk.CreateFilesystem() to fail on a 4GiB gpt partition because it said the size was > max FAT32 filesystem size.

**Comment by queuem** [comment]
Correct link to offending line: https://github.com/diskfs/go-diskfs/blob/master/partition/gpt/table.go#L521

**Comment by deitch** [comment]
Hmm... [here](https://github.com/diskfs/go-diskfs/blob/master/partition/gpt/partiton.go#L22) it is in bytes (and everywhere else that consumes it), but in [gpt.Table.GetPartitionSize()](
https://github.com/diskfs/go-diskfs/blob/master/partition/gpt/table.go#L521) it is multiplying the already-bytes-denominated field by the sector size, making it, e.g. 512*size-in-bytes (or whatever the sector size is)? Is that right?

I assume you came across this in a practical example. Do you mind pasting it here? We can use that code as part of tests, and I would like it documented here in the issue. PR is a one-line fix, but need the test first of course.

The other question is, if this is an error, why does [this test](https://github.com/diskfs/go-diskfs/blob/master/partition/gpt/table_test.go#L367) pass?

**Comment by deitch** [comment]
Drat. I figured it out. It tests against added partitions that do not have sizes, so it always is 0. First thing is to fix this test.

**Comment by deitch** [comment]
See #11, and thanks for finding this, @queuem !
