### ISSUE TITLE
[iso9660] Index out of range panic

### ISSUE THREAD

**Issue by mraerino** [diskfs/go-diskfs#103]
I'm getting this panic as part of running the [linuxkit metadata service](https://github.com/linuxkit/linuxkit/tree/master/pkg/metadata)

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/filesystem/iso9660.parseDirEntry(0xa60458, 0x0, 0x0, 0xc0000e4000, 0x17000, 0x0, 0x0)
	/go/src/github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/filesystem/iso9660/directoryentry.go:281 +0x789
github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/filesystem/iso9660.Read(0x818500, 0xc00000e068, 0x400000, 0x0, 0x1000, 0x1, 0x8122e0, 0xc000010ed0)
	/go/src/github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/filesystem/iso9660/iso9660.go:223 +0x965
github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/disk.(*Disk).GetFilesystem(0xc000078230, 0x0, 0x0, 0xc000078230, 0x0, 0x0)
	/go/src/github.com/linuxkit/linuxkit/pkg/metadata/vendor/github.com/diskfs/go-diskfs/disk/disk.go:227 +0x241
```

when i mount the cdrom in linux it works fine and i can list the files on it and view them

here is an image of the cdrom: [broken-cdrom.img.gz](https://github.com/diskfs/go-diskfs/files/6240080/broken-cdrom.img.gz)

**Comment by mraerino** [comment]
_ok, i did some more investigation into this_

looks like this is caused by a wrongly detected physical block size on the device.
- `iso9660.Read(f, 0, 0, 2048)` works fine
- `iso9660.Read(f, 0, 0, 4096)` panics

I think it should not panic, but produce an error instead

**Comment by deitch** [comment]
@mraerino could you share a simple program that can replicate this?

**Comment by mraerino** [comment]
i put a test here which panics: https://github.com/diskfs/go-diskfs/pull/105

**Comment by deitch** [comment]
Please try the branch with the PR at #106
