### ISSUE TITLE
fat32.File does not not implement io.Writer correctly.

### ISSUE THREAD

**Issue by RafaelMarinheiro** [diskfs/go-diskfs#108]
It seems that multiple calls to `fat32.File.Write()` will simply cause previous writes to be overwritten. This is pretty noticeable if one tries to call io.Copy a large reader (32KB+) into it:

```
var src os.File = io.Open(...)
dest, _ = destfs.OpenFile(path, os.O_CREATE|os.O_RDWR)
written, err := io.Copy(dest, src) 
``` 

In this scenario io.Copy will report all src bytes as written and no error is reported. The final file will contain only the last 32KB of the original file (that's because 32KB is the default buffer size used by io.Copy).

**Comment by deitch** [comment]
Hey @RafaelMarinheiro I am not sure I get the issue. `io.Copy()` has a default buffer of 32KB, but it should loop through reading from `src` until it gets an `io.EOF` (or other `error`, of course, but that never happens 😄 )

Can you whip up a functional program that full recreates the issue and shows it?

**Comment by RafaelMarinheiro** [comment]
The problem here is that `io.Copy` calls `fat32.File.Write` multiple times and it seems that `fat32.File.Write` does not update the `fat32.File.offset` field. Because of that you simply overwrite the same region over and over. I'll try to come up with a test for that.

**Comment by RafaelMarinheiro** [comment]
I was going to write a test for this, but it seems that TestFat32OpenFile/Large_Fire and TestFat32OpenFile/Streaming_Large_File are trying to cover this but they are already failing. I guess that fixing those tests should fix this bug.

**Comment by deitch** [comment]
This is strange. I totally believe you - and I was able to recreate it - but `go test` is part of CI, why did it not capture it on previous runs?

A different problem for a different day. At least we have a solid recreation now.
