### ISSUE TITLE
Request: tag a new release

### ISSUE THREAD

**Issue by AkihiroSuda** [diskfs/go-diskfs#117]
The latest release was more than a year ago.
Any chance to ship a new release? :pray:

**Comment by deitch** [comment]
Sure. I figured most people would just take an explicit commit, so didn't bother with it. That, and the fact that I have qcow2 working as read and half of write, and ext4 working as read, but not write, and keep hoping that they would be done in time for a new release.

We will cut a tag shortly.

**Comment by deitch** [comment]
Just tagged v1.2.0 :-)

**Comment by AkihiroSuda** [comment]
thanks！
