### ISSUE TITLE
change uuid of disk and partition inside raw image

### ISSUE THREAD

**Issue by vtolstov** [diskfs/go-diskfs#12]
I have some sort of cloud hosting. Main problem now, that all os installed from already created images (say snapshots).and have identical uuid of disks and partitions, but when i'm attach to already booted server image with system from another server i have identical uuid of different disks and identical partition uuid.
What is the best way to avoid this? I think about after create image from snapshot modify gpt partition table and set empty uuid, so go-diskfs generate new.
May be i miss something?

**Comment by deitch** [comment]
Hi @vtolstov . Not sure I understand the question. You build a disk image (e.g. AMI on AWS), and use it to boot multiple instances. Now each has the same UUIDs for disks and partitions (assuming GPT, which has much sane partition GUIDs). Your problem now is that you want unique GUIDs (which is the point of them).

I see two possibilities:

1. Have a boot-time process on your OS (in `systemd` or wherever) that runs once to reset it using typical tools.
2. Have a pre-publish tool that manipulates it.

The problem with the second option is that you would need to generate a unique image for every server you boot, which hardly is scalable.

`go-diskfs` is a library for inclusion in other golang programs to manipulate images. You _could_ integrate `go-diskfs` in some tool that works the first solution, but why wouldn't you just use sgdisk or something else off the shelf?

**Comment by vtolstov** [comment]
@deitch i think about 1, but how to know does i  need to change guid or not? i need to change it only on first start.. i can create some lock file in /var.. but if i can't read it...?

**Comment by deitch** [comment]
Save the GUID somewhere on the filesystem. On first boot, if the flag exists, switch the guid and remove the file, else do nothing.

It is a bit out of scope for this, though.

**Comment by vtolstov** [comment]
Thanks
