### ISSUE TITLE
Disk.Table is not populated without partition write

### ISSUE THREAD

**Issue by iancoolidge** [diskfs/go-diskfs#120]
It is useful to be able to open a 'Disk' structure for reading, such as in a unit test.

this is not possible currently, as Disk.Table is only populated when writing a partition table to disk, which is a potentially destructive operation.

it should be possible to poulate Disk.Table from a partition read.

**Comment by deitch** [comment]
Yeah, that makes sense. It should go in [here](https://github.com/diskfs/go-diskfs/blob/master/disk/disk.go#L52-L54). Would be happy to take a PR :-)

**Comment by deitch** [comment]
Fixed with #121
