### ISSUE TITLE
Go modules

### ISSUE THREAD

**Issue by alkersan** [diskfs/go-diskfs#13]
I propose to move dependency management to [go modules](https://github.com/golang/go/wiki/Modules). Benefits:
 - one less extra tool needed (i.e. `dep`), as module management is embedded into go now
 - development in a `GOPATH`-independent environment

**Comment by deitch** [comment]
Definitely. I’ve been moving other projects over slowly. This is a good one for it. If you have time, open a PR?

**Comment by alkersan** [comment]
Sure, i'll prepare PR soon.

**Comment by deitch** [comment]
Closed via #22
