### ISSUE TITLE
support creating 4K raw images via Create (or new function)?

### ISSUE THREAD

**Issue by anonymouse64** [diskfs/go-diskfs#133]
Hi,

We have a bunch of code in snapd / Ubuntu Core around creating partitions / structures that now via the ubuntu-image rewrite uses this library (see https://github.com/canonical/ubuntu-image for details, specifically `makeDisk()` in common_states.go) to create a raw .img file for a volume that then gets flashed to a device (or in the case of our tests used in a VM)

It would be great both for creating images for consumption on physical media that has 4K physical sector size / block size and for our own VM based testing to be able to create disk images via some option that use 4K as the sector size instead of the default 512 that is currently hard-coded here in diskfs.go.

Maybe a new function CreateWithSectorSize or some additional Format flag in Create()? 

Thanks,
Ian

**Comment by deitch** [comment]
> We have a bunch of code in snapd / Ubuntu Core around creating partitions / structures that now via the ubuntu-image rewrite uses this library

Great!

> It would be great both for creating images for consumption on physical media that has 4K physical sector size / block size and for our own VM based testing to be able to create disk images via some option that use 4K as the sector size instead of the default 512 that is currently hard-coded here in diskfs.go

Right. If it is an actual block device, it reads it from the block device [here](https://github.com/diskfs/go-diskfs/blob/308c225a001f5d58a273bddc2d1732a2162a6e10/diskfs.go#L206); if not, it just assumes 512 bytes [here](https://github.com/diskfs/go-diskfs/blob/308c225a001f5d58a273bddc2d1732a2162a6e10/diskfs.go#L175-L176)

It sounds reasonable to be able to override it. 

> Maybe a new function CreateWithSectorSize or some additional Format flag in Create()?

I think an additional flag is better than a proliferation of functions. We easily could have more parameters in the future, which can make it unwieldy. Granted, this is just a stylistic preference, but I am allowed to prefer. :-)

I have used variadic parameters in the past to keep things from growing too much or changing a signature, but that seems overkill here. Let's just add a parameter. On the other hand, that does break the existing API, which semver would indicate should cut a new release. I have no great desire to cut 2.0.0 just for this.

Eh, let's go for the parameter and not worry too much about semver's strict rules here.

Care to open a PR for it?

**Comment by anonymouse64** [comment]
Thanks @sil2100  for working on this!
