### ISSUE TITLE
Custom iso volume identifier

### ISSUE THREAD

**Issue by alkersan** [diskfs/go-diskfs#14]
Finalized iso is labeled [`ISOIMAGE`](https://github.com/diskfs/go-diskfs/blob/master/filesystem/iso9660/finalize.go#L644) at the moment. It would be great to make this customisable, for example to create [cloud-init seed](https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html) image, which require the iso to be labeled with `CIDATA`.

**Comment by deitch** [comment]
Easy enough to add it to `FinalizeOptions`. That is what it is there for....
