### ISSUE TITLE
Where is the type `PartitionTable` defined?

### ISSUE THREAD

**Issue by netjune** [diskfs/go-diskfs#146]
It is used in the example code. But I cant find the definition.

```
table := PartitionTable{
	type: partition.GPT,
	partitions:[
		Partition{Start: partitionStart, End: partitionEnd, Type: partition.EFISystemPartition, Name: "EFI System"}
	]
}
// apply the partition table
err = disk.Partition(table)
```

And how to delete all partitions of a disk?

**Comment by deitch** [comment]
I assume you mean the sample on the `README.md` home page? It depends on the type of disk you are creating. gpt table is [here](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.2.0/partition/gpt#Table) mbr table is [here](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.2.0/partition/mbr#Table)

**Comment by deitch** [comment]
> how to delete all partitions of a disk?

That depends on if you want to just remove them from the table (fast erase), such that they don't show up, or actually zero out the data (secure erase). For fast erase, just create a new partition table and write it to the disk. It overwrites the old one.

For secure erase, you would need to write contents of all 0 to the partition table, e.g. [mbr.WriteContents()](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.2.0/partition/mbr#Partition.WriteContents)

**Comment by netjune** [comment]
> I assume you mean the sample on the `README.md` home page? It depends on the type of disk you are creating. gpt table is [here](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.2.0/partition/gpt#Table) mbr table is [here](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.2.0/partition/mbr#Table)

Yes. I see mbr.Table. But I dont know how to construct it. How to set `LogicalSectorSize` and `PhysicalSectorSize`?
I have the disk opened(object name is `disk`). Can I get the above 2 values from the disk object?


> That depends on if you want to just remove them from the table (fast erase), such that they don't show up, or actually zero out the data (secure erase). For fast erase, just create a new partition table and write it to the disk. It overwrites the old one.
The fast erase.

**Comment by netjune** [comment]
I just want to delete all partitions of /dev/sdd. I use the following code:

```
package main

import (
	"fmt"
	"os"

	diskfs "github.com/diskfs/go-diskfs"
	"github.com/diskfs/go-diskfs/partition/mbr"
)


func main() {
	d, err := diskfs.Open("/dev/sdd", diskfs.WithOpenMode(diskfs.ReadWriteExclusive))
	if err != nil {
		fmt.Printf("### open disk error! %s\n", err.Error())
		os.Exit(1)
	}

	t := &mbr.Table{
		LogicalSectorSize: 512,
		PhysicalSectorSize: 512,}

	err = d.Partition(t)
	if err != nil {
		fmt.Printf("### partition error! %s\n", err.Error())
	} else {
		fmt.Printf("partition OK!\n")
	}
}
````````

The program is run by root. And the disk /dev/sdd is free(not mounted). But the disk cant be opened:
```### open disk error! Could not open device /dev/sdd exclusively for writing```

**Comment by deitch** [comment]
> These two values are hard for me to get. How to get the two values using this library?

See [here](https://manpages.courier-mta.org/htmlman8/fdisk.8.html) where you can set the sector size. I do believe that MBR defaults to 512, but don't rely on that.

**Comment by deitch** [comment]
> The program is run by root. And the disk /dev/sdd is free(not mounted). But the disk cant be opened:
### open disk error! Could not open device /dev/sdd exclusively for writing

Hmm, I assume `/dev/sdd` exists? Are you running inside a container which might not have the correct capabilities? It is just using a normal `os.OpenFile()` [here](https://github.com/diskfs/go-diskfs/blob/8ff8bc623cffbe3d41db4bcc902bca9823abfa22/diskfs.go#L326)

Can you mount the disk? Can you open it just to read, e.g.

```bash
dd if=/dev/sdd of=/tmp/foo bs=10 count=100
```
