### ISSUE TITLE
How to close the disk?

### ISSUE THREAD

**Issue by netjune** [diskfs/go-diskfs#150]
```
        disk, err := diskfs.Open(p)
	if err != nil {
		log.Panic(err)
	}
```
I didn't find  `Close` method.

**Comment by deitch** [comment]
That's a good point. The `diskfs.Open()` method is [here](https://github.com/diskfs/go-diskfs/blob/master/diskfs.go#L309-L333), where it calls [os.OpenFile()](https://github.com/diskfs/go-diskfs/blob/master/diskfs.go#L327), but has no option to `Close()`, which should just (safely) close the underlying disk file or device.

Go for a PR on it?
