### ISSUE TITLE
Any plans for a release version?

### ISSUE THREAD

**Issue by adamqqqplay** [diskfs/go-diskfs#167]
It has been more than a year since the release of v1.2.0. I would like to ask if it is possible to release the next version, such as v1.2.1, so that developers in the go community can use new features.

**Comment by deitch** [comment]
Sure, no objections. Looking at the list of changes and seeing if it qualifies as 1.3.0 or 1.2.1

**Comment by deitch** [comment]
Definitely a v1.3.0 for that. Done. Thanks for suggestion @adamqqqplay

**Comment by adamqqqplay** [comment]
> Definitely a v1.3.0 for that. Done. Thanks for suggestion @adamqqqplay

Thanks for your great work!
