### ISSUE TITLE
Support status for solaris, aix, freebsd, illumos, netbsd, openbsd and plan9

### ISSUE THREAD

**Issue by yadutaf** [diskfs/go-diskfs#171]
For the context, I'm currently looking on introducing Windows support for the block devices. This work would quite logically require moving a bit of code around, and I came to realize that this project currently supports all platforms.

However, in practice, this is a very challenging target especially for block devices where OS-specific interaction is needed to get basic information like the device type, device size, physical and logical block sizes, and so on.

For block devices, the current status looks like:

* Darwin: Full support, with dedicated code
* Other Unix and Plan9: Full support, with generic code
* Windows: Only file based support (no block device)

However, in practice, this is more like:

* Linux: Full support
* Darwin: Full support
* Windows: File-based support
* Other platforms: _Broken build_

```
for o in linux darwin windows solaris aix freebsd illumos netbsd openbsd plan9; do echo "Testing with $o..."; GOOS=$o go build . && echo "--> OK" || echo "--> FAIL"; done
Testing with linux...
--> OK
Testing with darwin...
--> OK
Testing with windows...
--> OK
Testing with solaris...
# github.com/diskfs/go-diskfs
./diskfs_unix.go:20:62: undefined: unix.BLKSSZGET
./diskfs_unix.go:24:63: undefined: unix.BLKPBSZGET
--> FAIL
Testing with aix...
go: unsupported GOOS/GOARCH pair aix/amd64
--> FAIL
Testing with freebsd...
# github.com/diskfs/go-diskfs
./diskfs_unix.go:20:62: undefined: unix.BLKSSZGET
./diskfs_unix.go:24:63: undefined: unix.BLKPBSZGET
--> FAIL
Testing with illumos...
# github.com/diskfs/go-diskfs
./diskfs_unix.go:20:62: undefined: unix.BLKSSZGET
./diskfs_unix.go:24:63: undefined: unix.BLKPBSZGET
--> FAIL
Testing with netbsd...
# github.com/diskfs/go-diskfs
./diskfs_unix.go:20:62: undefined: unix.BLKSSZGET
./diskfs_unix.go:24:63: undefined: unix.BLKPBSZGET
--> FAIL
Testing with openbsd...
# github.com/diskfs/go-diskfs
./diskfs_unix.go:20:62: undefined: unix.BLKSSZGET
./diskfs_unix.go:24:63: undefined: unix.BLKPBSZGET
--> FAIL
Testing with plan9...
# github.com/pkg/xattr
../go/pkg/mod/github.com/pkg/xattr@v0.4.9/xattr_unsupported.go:13:20: undefined: syscall.Errno
../go/pkg/mod/github.com/pkg/xattr@v0.4.9/xattr.go:112:21: undefined: syscall.ERANGE
../go/pkg/mod/github.com/pkg/xattr@v0.4.9/xattr.go:116:52: undefined: syscall.EOVERFLOW
# github.com/diskfs/go-diskfs/filesystem/iso9660
filesystem/iso9660/statt_others.go:14:32: undefined: syscall.Stat_t
--> FAIL
```

Considering only Linux, Darwin and Windows can be correctly built, we probably can assume that the other platforms are not targeted in the wild. I thus propose to officially remove Solaris, Aix, FreeBSD, Illumos, MetBSD, OpenBSD and Plan9 from the build and of course mention it in the Readme.

I see the following benefit:
* Clarity for users
* Simplified maintenance and support for contributors since we know exactly was is supported and what is not
* (future) Paves the road to get block size using platform specific IOCTL instead of Open+Seek based method (which looks generic for Unix)
* Simplifies the refactoring needed to bring Windows support for block devices

If this plan looks reasonable to you, I can open PRs to first remove other Unix support and then move block size query to Ioctl on Darwin and Linux.

**Comment by deitch** [comment]
Other than the build directives, nothing in the documentation says anything about aix or plan9 or illumos etc. Why not just leave them in there? How does it not add clarity. We probably should add support, it is a question of finding time for figuring out how to do each platform in its own unique way.

How does it get in the way of the Windows refactoring? Just change `diskfs_windows.go`.

**Comment by yadutaf** [comment]
Oh! You are absolutely right, it does not really get in the way of Windows support. This is more something I stumbled upon when working on it. Indeed, to add this support, the biggest part of `initDisk` needs to be refactored into OS-specific parts as `f.Stat()` fails for block devices on Windows. However, it remains largely the same as it is today for all other platforms and should therefore be shared.

This led to a messy file tree looking like:

* `diskfs.go`
* `diskfs_darwin.go` for the Darwin specific code
* `diskfs_unix.go` for the non-Darwin part of the detection code
* `diskfs_common_unix.go` for the bulk of the detection code
* `diskfs_windows.go` for the Windows specific code

Based on this and your comment, would something like this be more acceptable ?

* `diskfs.go`: No major change, just move out some OS-Specific code
* `diskfs_darwin.go`: Mostly as today, for Darwin specific code
* `diskfs_linux.go`: Mostly the current `disks_unix.go`, officially Linux specific though
* `diskfs_windows.go`: *future*. For Windows specific code, with block device support
* `diskfs_other.go`: *new*.  Stub implementation for all other platforms with file support and no block support
* `diskfs_unix.go`: *new*. For common code across all Unix variants (that is, the file vs block detection logic currently in `initDisk`)

And of course, add at least a compile-test for these platforms :smile: 

If this looks more reasonable, I can either open a dedicated PR to initiate the files, or keep this as preparation commits for the Windows work and have all reviewed together.

**Comment by deitch** [comment]
Sure, that makes sense. I don't think either is all _that_ messy. Go for it. Thanks for contributing. Smaller PRs always are better (I say, as I have a massive one for ext4 in the works for a long time 😄 ), so go for it.
