### ISSUE TITLE
Support to remove files

### ISSUE THREAD

**Issue by ludelion5** [diskfs/go-diskfs#191]
Hi, thanks for the awesome library.

I played around a bit with the library and was able to create new files and upate existing files on a fat32 partition inside an image. Unfortunately, there seems to be no support for removing files. Do I miss something? If its really missing, will the remove functionality come in the future?

Thanks and best regards

**Comment by deitch** [comment]
Right you are. Never got to implementing delete. Of course, some filesystems are read-only (iso and squashfs), so that would fail. And it supports mkdir and creating files and modifying partition tables on disks. But, yes, deleting never got created.

A contribution would be most welcome.

**Comment by deitch** [comment]
That would be great, thank you. I am sorry you have to go through the approvals rigamarole, but it isn't uncommon in large firms.
