### ISSUE TITLE
Be able to compile to webassembly wasm

### ISSUE THREAD

**Issue by rgl** [diskfs/go-diskfs#207]
It would be pretty nice to be able to target wasm.

Currently with with go 1.21.5 and go-diskfs 1.4.0. a simple program that creates a FAT32 disk image, is failing as:

```bash
GOOS=wasip1 GOARCH=wasm go build -o amt-setupbin-img.wasm
```
```
# gopkg.in/djherbis/times.v1
../../../../go/pkg/mod/gopkg.in/djherbis/times.v1@v1.3.0/times.go:11:9: undefined: getTimespec
../../../../go/pkg/mod/gopkg.in/djherbis/times.v1@v1.3.0/times.go:21:9: undefined: getTimespec
# github.com/sirupsen/logrus
../../../../go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/terminal_check_notappengine.go:13:10: undefined: isTerminal
# github.com/diskfs/go-diskfs/filesystem/squashfs
../../../../go/pkg/mod/github.com/diskfs/go-diskfs@v1.4.0/filesystem/squashfs/finalize.go:463:22: undefined: getFileProperties
../../../../go/pkg/mod/github.com/diskfs/go-diskfs@v1.4.0/filesystem/squashfs/finalize.go:1177:25: undefined: getDeviceNumbers
../../../../go/pkg/mod/github.com/diskfs/go-diskfs@v1.4.0/filesystem/squashfs/finalize.go:1202:25: undefined: getDeviceNumbers
```

**Comment by deitch** [comment]
It would be nice, indeed, to have a wasm target for it (it also would be nice if this didn't auto-correct "wasm" to "warm" 😁 ).

Of the issues you raised:

* `getFileProperties` and `getDeviceNumbers`: these have platform-specific functions, defined in [finalize_unix.go](https://github.com/diskfs/go-diskfs/blob/master/filesystem/squashfs/finalize_unix.go) and [finalize_windows.go](https://github.com/diskfs/go-diskfs/blob/master/filesystem/squashfs/finalize_unix.go). I do not know what the equivalent implementations for wasm would be; if you know, and want to add a `finalize_wasm.go`, I definitely would take that.
* `getTimespec` (from `gopkg.in/djherbis/times.v1`) - this one actually has some wasm support in v1.6.0, see [times_wasip1.go](https://github.com/djherbis/times/blob/v1.6.0/times_wasip1.go). We can bump the dependency here to v1.6.0, which should solve it. Check it locally, and if that issue goes away, open the PR on this.
* `isTerminal` (from `github.com/sirupsen/logrus`) is called [here](https://github.com/sirupsen/logrus/blob/v1.9.3/terminal_check_notappengine.go#L13C15-L13C15), and is defined on each platform: [solaris](https://github.com/sirupsen/logrus/blob/v1.9.3/terminal_check_solaris.go), [unix](https://github.com/sirupsen/logrus/blob/v1.9.3/terminal_check_unix.go) and [windows](https://github.com/sirupsen/logrus/blob/v1.9.3/terminal_check_windows.go). We have the latest semver, which does not have wasm support, but it looks like `master` branch does [here](https://github.com/sirupsen/logrus/blob/master/terminal_check_wasi.go). Go ahead and open a PR to bump this to latest. FYI, someone had a compilation issue, documented [here](https://github.com/sirupsen/logrus/issues/1394).

**Comment by rgl** [comment]
Thank you! I will look into your suggestions and will report back!

**Comment by rgl** [comment]
@deitch got it working at https://github.com/diskfs/go-diskfs/pull/208 :-)

please take a look.
