### ISSUE TITLE
Panic runtime error invalid memory with MBR partition on disk

### ISSUE THREAD

**Issue by saamalik** [diskfs/go-diskfs#25]
Hi,
I'm getting a _panic: runtime error: invalid memory address_ when creating a MBR partition on a real disk. 

**Error**:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4d1256]

goroutine 1 [running]:
github.com/diskfs/go-diskfs/disk.(*Disk).Partition(0x0, 0x536d60, 0xc000070690, 0x536520, 0xc000010640)
        /root/go/pkg/mod/github.com/diskfs/go-diskfs@v0.0.0-20190815060803-4a6168b3bc46/disk/disk.go:55 +0x26
main.main()
```

*Sample code*:
```go
	diskImg := "/dev/sdb"
	// disk, _ := diskfs.Create(diskImg, diskSize, diskfs.Raw)

	disk, _ := diskfs.Open(diskImg)

	table := &mbr.Table{
		LogicalSectorSize:  512,
		PhysicalSectorSize: 512,
		Partitions: []*mbr.Partition{
			{
				Bootable: false,
				Type:     mbr.Linux,
				Start:    2048,
				Size:     20480,
			},
		},
	}

	disk.Partition(table)
```

*Disks*:
```
[root@s-daba flash1]# lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0  40G  0 disk 
└─sda1   8:1    0  40G  0 part /
sdb      8:16   0   5G  0 disk
```

Manually creating _MBR Partition table_ using _fdisk_ on _/dev/sdb_ works as expected. Also, changing _diskImg_ to `/tmp/foo.img` also proceeds successfully.

**Comment by a2geek** [comment]
I don't think so, but feel free to try the `mbr-write` branch in my fork: https://github.com/a2geek/go-diskfs/tree/mbr-write

**Comment by deitch** [comment]
@a2geek are you saying that it is working fine with a disk image, but not pointing at a block device?

**Comment by deitch** [comment]
And I could replicate it by doing the same?

**Comment by a2geek** [comment]
My usage has strictly been with disk images (files) and not devices. Sorry, I didn't mean to confuse this issue at all...

**Comment by saamalik** [comment]
@deitch - yes, it's working fine with disk image, but not on a block device. You should be able to replicate; it doesn't work on CentOS7 (VirtualBox)

**Comment by deitch** [comment]
> My usage has strictly been with disk images (files) and not devices

When this whole thing started, that was the initial motivation as well, but it should work with both. Let's see if we can figure it out.

**Comment by deitch** [comment]
Sure, it has a problem. Look at the line:

```go
	disk, _ := diskfs.Open(diskImg)
```

You threw away the error without checking it. If you had, you would see errors:

```go
	disk, err := diskfs.Open(diskImg)
        if err != nil {
            log.Fatalf("unexpected error: %v", err)
        }
```

Without checking the error, you don't know. You also didn't check if the returned `disk` is `nil` (which it is if there is an error), hence the `nil pointer` problem and the `SIGSEGV`.

Try checking the error code and seeing why. Also make sure whatever user you are running it as has rights to write to the device.

Closing this issue. If you run it and see an unexpected error that doesn't make sense, go ahead and open a new specific issue.

**Comment by deitch** [comment]
FYI, the test files I used are at https://gist.github.com/deitch/e3129e7aa902d62a84aac7aa20cc8f30
