### ISSUE TITLE
How to create a simple iso image

### ISSUE THREAD

**Issue by kstieger** [diskfs/go-diskfs#37]
Hi,
I tried to follow the documentation on godoc. But I was not successful to create a simple iso image.
I tried this: https://gist.github.com/kstieger/3fa5b945a9008de91c974ddd611ab325#file-myiso-go

The iso file is generated, but when I try to mount it, I receive a error message:
```
$ mount -o loop /tmp/mydisk.iso /media/
mount: /media: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
```

Thanks a lot,
Kurt

**Comment by vtolstov** [comment]
Try adding -t iso9660 (may be error in digits, written in mobile)

ср, 13 нояб. 2019 г., 17:25 Kurt Stieger <notifications@github.com>:

**Comment by deitch** [comment]
My head hasn't been in iso for a bit (won't take long to get it back :-) ), but I don't think that you can have a partition inside an iso like that. An iso file should be the entire file.

**Comment by kstieger** [comment]
Thanks.
@vtolstov : tried this also, but didn't work.
@deitch: when I remove the partitioning stuff (line 27:40) I receive this:
```
2019/11/13 15:45:59 cannot create filesystem on a partition without a partition table
```
I've also trie it with Fat32 (changed filesystem.Type and Partition Type), but this also didn't work. Image was not mountable.

**Comment by deitch** [comment]
Will take a look...

**Comment by deitch** [comment]
@kstieger modified your gist, this appears to work https://gist.github.com/deitch/64c7dac7cef5a74f6745ad942fc70a5e . It certainly compiles and runs. I need to try the output iso though. Can you try and see?

**Comment by kstieger** [comment]
Hi,
thanks for helping.

But it still doesn't work. It seems that the file is empty.
If I do 'head mydisk.iso' the output is empty, if I do the same on an iso generated with 'mkisofs' I see some data describing a filesystem ....

Thanks,
Kurt

**Comment by deitch** [comment]
OK will need to dig a bit

**Comment by deitch** [comment]
This is what I get for not looking at iso in a while. See [this link](https://github.com/diskfs/go-diskfs#read-only-filesystems) . You need to finalize it. I updated the gist. However, I still am missing something, as it is not working correctly. But you do have a real file now. :-)

**Comment by deitch** [comment]
Ah, I think I have it...

**Comment by deitch** [comment]
Yup. There are two issues here:

* a bug in the iso9660 implementation. This is being fixed by #38 
* better example for iso9660. I will take your example, expand and fix it in the examples dir

Hang tight, it is coming soon...

**Comment by deitch** [comment]
Do you mind commenting on #39 @kstieger please?

**Comment by kstieger** [comment]
Thanks, it's fine for me.
Works like a charm.
