### ISSUE TITLE
dashes (-) in filenames on iso9660 images

### ISSUE THREAD

**Issue by kstieger** [diskfs/go-diskfs#40]
Hi,
I'm not sure why, but a regexp in filesystem/iso9660/finalize.go and filesystem/iso9660/directoryentry.go sanitizes the filenames and replaces dashes (-) with underscores (_).
Afaik is a dash in a filename valid. 
I changed this, added a '-' to regexp, and it looks good and works.
Should I create a PR or is there any risk in my solution?
Thanks,
Kurt

**Comment by deitch** [comment]
I assume you are referring to [this](https://github.com/diskfs/go-diskfs/blob/master/filesystem/iso9660/finalize.go#L838)?

In ISO9660, a filename must be composed of d-characters, see section 7.5.1 of the ECMA-119 reference [here](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-119.pdf). Those are `[A-Z0-9_]` and do not include `-` (essentially, the same as MS-DOS). You _can_ use other characters when doing things like Rock Ridge and other extensions. But not in the basic iso9660.

**Comment by kstieger** [comment]
Ah, ok thanks, didn't know about that.
My problem is, cloud-init (in NoCloud mode) depends on on an iso with files including dashes in their name (user-data, meta-data, ...).
Is there a plan to implement the Rock Ridge extension to go-diskfs?
thanks, Kurt

**Comment by deitch** [comment]
It’s already there. Look at the options for finalizing an iso here https://godoc.org/github.com/diskfs/go-diskfs/filesystem/iso9660#FinalizeOptions

**Comment by kstieger** [comment]
Yes, thanks.
Now it works as expected.
Many thanks for your help.
