### ISSUE TITLE
fat32 labels

### ISSUE THREAD

**Issue by rmb938** [diskfs/go-diskfs#46]
When creating a fat32 filesystem with a volume label it doesn't label it correctly

```golang
cloudInitFS, err := destDisk.CreateFilesystem(disk.FilesystemSpec{
  Partition:   1,
  FSType:      filesystem.TypeFat32,
  VolumeLabel: "config-2",
})
```

Running `blkid` shows that the label applied is `LABEL_FATBOOT="config-2"` instead of `LABEL="config-2"`. 

When I run the `fatlabel` utility to add a label manually it does it correctly by setting `LABEL` as well.

**Comment by deitch** [comment]
Hi @rmb938 I don't see it:

```sh
$ file /tmp/foo.img
/tmp/foo.img: DOS/MBR boot sector, code offset 0x58+2, OEM-ID "godiskfs", Media descriptor 0xf8, sectors/track 1, heads 1, sectors 20480 (volumes > 32 MB), FAT (32 bit), sectors/FAT 159, serial number 0xfd42e9f9, label: "config-2   "
$ blkid /tmp/foo.img
/tmp/foo.img: LABEL="config-2" UUID="FD42-E9F9" TYPE="vfat"
```

I did it pretty simply:

```go
package main

import (
	"fmt"
	"log"
	"os"

	diskfs "github.com/diskfs/go-diskfs"
	"github.com/diskfs/go-diskfs/disk"
	"github.com/diskfs/go-diskfs/filesystem"
)

func check(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
func CreateFS(diskImg string) {
	if diskImg == "" {
		log.Fatal("must have a valid path for diskImg")
	}
	var diskSize int64
	diskSize = 10 * 1024 * 1024 // 10 MB
	mydisk, err := diskfs.Create(diskImg, diskSize, diskfs.Raw)
	check(err)

	//mydisk.LogicalBlocksize = 2048
	fspec := disk.FilesystemSpec{Partition: 0, FSType: filesystem.TypeFat32, VolumeLabel: "config-2"}
	fs, err := mydisk.CreateFilesystem(fspec)
	check(err)
	fmt.Printf("%#v\n", fs)
}

func main() {
	if len(os.Args) < 2 {
		fmt.Printf("Usage: %s <outfile>\n", os.Args[0])
		os.Exit(1)
	}
	CreateFS(os.Args[1])
}
```

I do see that you have it a `Partition: 1`, implying there is a partition table there, whereas I did it with `Partition: 0` across the whole disk. I wonder if that might be it? Post your entire chunk of code here?

**Comment by rmb938** [comment]
Huh interesting. So it works fine when creating images but doesn't work when using actual disk devices.

```golang
package main

import (
	"fmt"
	"log"
	"os"

	diskfs "github.com/diskfs/go-diskfs"
	"github.com/diskfs/go-diskfs/disk"
	"github.com/diskfs/go-diskfs/filesystem"
	"github.com/diskfs/go-diskfs/partition/mbr"
)

func check(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
func CreateFS(diskImg string) {
	if diskImg == "" {
		log.Fatal("must have a valid path for diskImg")
	}
	mydisk, err := diskfs.Open(diskImg)
	check(err)

	table := &mbr.Table{
		LogicalSectorSize:  512,
		PhysicalSectorSize: 512,
		Partitions: []*mbr.Partition{
			{
				Bootable: false,
				Type:     mbr.Linux,
				Start:    2048,
				Size:     2097152, // 1GB of space for the partition
			},
		},
	}

	log.Print("Writing partition table to disk")
	err = mydisk.Partition(table)
	check(err)

	fspec := disk.FilesystemSpec{Partition: 1, FSType: filesystem.TypeFat32, VolumeLabel: "config-2"}
	fs, err := mydisk.CreateFilesystem(fspec)
	check(err)
	fmt.Printf("%#v\n", fs)
}

func main() {
	if len(os.Args) < 2 {
		fmt.Printf("Usage: %s <outfile>\n", os.Args[0])
		os.Exit(1)
	}
	CreateFS(os.Args[1])
}
```

![CaptureScreen](https://user-images.githubusercontent.com/544545/73136700-1ee4f100-4016-11ea-9736-85099ddbf01c.jpeg)

**Comment by deitch** [comment]
Well that _is_ interesting. I’ll spin up a cloud vm when I have a moment and replicate this, see if i can figure it out.

**Comment by deitch** [comment]
Just spun up an aws instance, attached an EBS volume as /dev/xvdb, ran it as follows:

```
[ec2-user@ip-172-31-40-76 fat32]$ sudo ./fat32 /dev/xvdb
2020/01/26 15:15:50 Writing partition table to disk
&fat32.FileSystem{bootSector:fat32.msDosBootSector{jumpInstruction:[3]uint8{0xeb, 0x58, 0x90}, oemName:"godiskfs", biosParameterBlock:(*fat32.dos71EBPB)(0xc0000820a0), bootCode:[]uint8{}}, fsis:fat32.FSInformationSector{freeDataClustersCount:0xffffffff, lastAllocatedCluster:0xffffffff}, table:fat32.table{fatID:0xffffff8, eocMarker:0xfffffff, clusters:map[uint32]uint32{0x2:0xfffffff}, rootDirCluster:0x2, size:0xffe00, maxCluster:0x3ff80}, dataStart:0x203c00, bytesPerCluster:4096, size:1073741824, start:1048576, file:(*os.File)(0xc000010030)}
[ec2-user@ip-172-31-40-76 fat32]$ lsblk -o name,kname,maj:min,label /dev/xvdb
NAME    KNAME MAJ:MIN LABEL
xvdb    xvdb  202:16
└─xvdb1 xvdb1 202:17  config-2
```

Looks right, doesn't it? Did you do something different? I see loopback devices?

**Comment by rmb938** [comment]
Huh, no I didn't do anything different.

I'm running my code in a Fedora 31 livecd that's why there are loop devices. 

Weird :man_shrugging:

**Comment by deitch** [comment]
Any chance you have a public VM I can access?

**Comment by rmb938** [comment]
I just spun up a fedora 31 box on digital ocean and was able to replicate it.

Send me your public ssh key and I can get you access.

**Comment by deitch** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCGj5PWE3cGGxb4yyfokthNS4coWai+ZguRMWd9Rv8rJ14TLNsYoI3czTypaB67cG/Zx+1Q4Y3tYfcXyW/iBDiKEeSpK4x1t6FdPLWsNrFT5EEsNzQY5oYpzDx7fU3W6nGveUL4swflwFiY6H7zS/S27jV4CESrTY0WGcwcell3a79nOWfqyrSIEhGCyrQXycfYMguCjGmKyD0CoDjWbbpn9OjEn3EHHvAGWI2NJ93hm0sc0or5QAcsR/N5hX5cSwHoXyTgV1EYuDffHKOGy44mLsFyrzsDn+DN38ITPrpmxtNKSqztfyDXAZqAeNK8jxRt5kxSKvi1JknirGbD7ifl

**Comment by rmb938** [comment]
`ssh root@64.225.47.152` should get you access

**Comment by deitch** [comment]
This _is_ interesting, see [here](https://cdn.kernel.org/pub/linux/utils/util-linux/v2.33/v2.33-rc1-ChangeLog). v2.33-rc1 and later have the following in the changelog:

```
commit 0d2e8ff94d0b222b3831fb31f1268dbcd566f30c
Author: Pali RohÃ¡r <pali.rohar@gmail.com>
Date:   Sat Nov 25 12:48:32 2017 +0100

    blkid: Encode any field which starts with LABEL in same way as LABEL field
    
    This applies also for LABEL_FATBOOT which contains bytes according to DOS
    code page and therefore does not contain valid UTF-8 sequence.
    
    Signed-off-by: Pali RohÃ¡r <pali.rohar@gmail.com>

 misc-utils/blkid.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

commit f0ca7e80d7a171701d0d04a3eae22d97f15d0683
Author: Pali RohÃ¡r <pali.rohar@gmail.com>
Date:   Sat Nov 25 12:48:18 2017 +0100

    libblkid: vfat: Change parsing label in special cases
    
    * Use only label from the root directory and do not fallback to the label
      stored in boot sector. This is how MS-DOS 6.22, MS-DOS 7.10, Windows 98,
      Windows XP and also Windows 10 behave. Moreover Windows XP and Windows 10
      do not touch label in boot sector anymore, so removing FAT label on those
      Windowses leads to having old label still stored in boot sector (which
      MS-DOS and Windows fully ignore).
    
    * Label entry "NO NAME" in root directory is treated as label "NO NAME"
      instead of empty label. In root directory it has no special meaning.
      String "NO NAME" has a special meaning (empty label) only for label
      stored in boot sector.
    
    * Label from the boot sector is now stored into LABEL_FATBOOT field. So if
      there are applications which depends or needs to read this label, they
      have ability.
    
    After this change LABEL always correspondent to the label from the root
    directory and LABEL_FATBOOT to the label stored in the boot sector. If some
    of those labels is missing or is not present (e.g. "NO LABEL" in boot
    sector) then particular field is not set.
    
    Signed-off-by: Pali RohÃ¡r <pali.rohar@gmail.com>

 libblkid/src/superblocks/vfat.c | 12 +++++++-----
 1 file changed, 7 insertions(+), 5 deletions(-)
```

Basically, blkid and lsblk have changed. Your Fedora is running util-linux 2.34, the Amazon Linux I tested on is running 2.30.2. 

Fedora:

```
[root@fedora-s-1vcpu-1gb-sfo2-01 fat32labels]# lsblk --version
lsblk from util-linux 2.34
```

Amazon Linux 2:

```
[ec2-user@ip-172-31-40-76 twice]$ lsblk --version
lsblk from util-linux 2.30.2
```

So the library _is_ doing the right thing, but the util-linux is interpreting it differently.

This leads to an interesting question: is it possible to label the partition in such a way that _both_ versions of util-linux will handle it correctly?

**Comment by rmb938** [comment]
Did some more testing and this also prevents the partition from showing up in `/dev/disk/by-label`.

**Comment by deitch** [comment]
What happens when using user-space FAT32 utilities? What shows up in `/dev/disk/by-label/`?

**Comment by deitch** [comment]
Come to think of it, I am pretty sure that `udev` itself just calls `blkid`, but not 100% sure.

**Comment by rmb938** [comment]
When calling `fatlabel` to get the label it returns currently as `config-2`.

When using `fatlabel` to label the filesystem it shows up in `/dev/disk/by-label` and `blkid` shows the correct `LABEL="config-2"` on the partition.  

So it probably is using blkid which is not returning the label correctly.

**Comment by deitch** [comment]
The source to `fatlabel` is [here](https://github.com/dosfstools/dosfstools), specifically it writes it [here](https://github.com/dosfstools/dosfstools/blob/master/src/boot.c#L755-L764). Interestingly, it writes both a boot label and a volume label:

```c
void write_label(DOS_FS * fs, char *label)
{
    int l = strlen(label);

    while (l < 11)
	label[l++] = ' ';

    write_boot_label(fs, label);
    write_volume_label(fs, label);
}
```

I don't truly feel like reading through the code to reverse engineer what it does.

Reading through the above comment, it looks like it is labeling the root directory, rather than the boot volume. A directory entry _does_ have a flag indicating the entry may be a volume label.

Since you have that system, can you create a small fat32 filesystem, label it correctly as you have it with something I will recognize, max 11 chars ("belgrave123"? :-) ) and load it up somewhere I can download it and look at the bits? I can compare it on multiple systems.

**Comment by rmb938** [comment]
Sure, do you want me to create the image all manually or via go-diskfs and then just label it manually?

**Comment by deitch** [comment]
Actually, since you are offering, do one all go-diskfs and one all manual. That way I really can do a byte to byte comparison (minus timestamps, etc.), but of the key areas. Maybe it will preemptively highlight other things.

**Comment by deitch** [comment]
Thanks for doing it, much appreciated. Do you mind posting your exact commands and code you used to generate these?

**Comment by deitch** [comment]
That was very helpful. Here is the beginning of the filesystem of the manual one:

```
00100000: eb58 906d 6b66 732e 6661 7400 0202 2000  .X.mkfs.fat... .
00100010: 0200 0000 50f8 0000 3d00 2200 0008 0000  ....P...=.".....
00100020: 0000 0000 5000 0000 0000 0000 0200 0000  ....P...........
00100030: 0100 0600 0000 0000 0000 0000 0000 0000  ................
00100040: 8000 2943 7ae5 8b62 656c 6772 6176 6531  ..)Cz..belgrave1
00100050: 3233 4641 5433 3220 2020 0e1f be77 7cac  23FAT32   ...w|.
```

And for the go-diskfs one:

```
00100000: eb58 9067 6f64 6973 6b66 7300 0201 2000  .X.godiskfs... .
00100010: 0200 0000 00f8 0000 0100 0100 0000 0000  ................
00100020: 0050 0000 9f00 0000 0000 0000 0200 0000  .P..............
00100030: 0100 0600 0000 0000 0000 0000 0000 0000  ................
00100040: 8000 29ee ae62 c262 656c 6772 6176 6531  ..)..b.belgrave1
00100050: 3233 4641 5433 3220 2020 0000 0000 0000  23FAT32   ......
```

They _both_ write the volume label at position 71 (or 60 in the ebpb, after the 11 of the header and OEM name). In that respect, they are the same. However, if you go to the root directory entry, the difference shows up.

The go-diskfs one has no entries in the root directory, because, well, there is nothing.

On the other hand, the manual one has the following:

```
00118000: 6265 6c67 7261 7665 3132 3308 0000 52be  belgrave123...R.
00118010: 3c50 3c50 0000 52be 3c50 0000 0000 0000  <P<P..R.<P......
```

Directory entries are 32 bytes, but the relevant bits here are the first 11 bytes (0x00-0x0a) - filename plus extension, in this case the volume name - and byte 0x0b, attributes, which is 0x08, i.e. bit 3 is set, indicating this is a volume label.

So for compatibility, we would need to also add that entry.

**Comment by rmb938** [comment]
Here are the commands and code, before running each one I attached a new disk to the vm just to make sure it was completely clean

### go-diskfs

```
go run fat_label.go /dev/sda 
dd if=/dev/sda of=go-diskfs.img
```

```golang
package main

import (
	"fmt"
	"log"
	"os"

	diskfs "github.com/diskfs/go-diskfs"
	"github.com/diskfs/go-diskfs/disk"
	"github.com/diskfs/go-diskfs/filesystem"
	"github.com/diskfs/go-diskfs/partition/mbr"
)

func check(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func CreateFSAndDir(diskImg string) {
	if diskImg == "" {
		log.Fatal("must have a valid path for diskImg")
	}
	mydisk, err := diskfs.Open(diskImg)
	check(err)

	cloudInitSize := 10 * 1024 * 1024 // 10 MB
	cloudInitSectors := uint32(cloudInitSize / 512)

	table := &mbr.Table{
		LogicalSectorSize:  512,
		PhysicalSectorSize: 512,
		Partitions: []*mbr.Partition{
			{
				Bootable: false,
				Type:     mbr.Linux,
				Start:    2048,
				Size:     cloudInitSectors,
			},
		},
	}

	log.Print("Writing partition table to disk")
	err = mydisk.Partition(table)
	check(err)

	fspec := disk.FilesystemSpec{Partition: 1, FSType: filesystem.TypeFat32, VolumeLabel: "config-2"}
	_, err = mydisk.CreateFilesystem(fspec)
	check(err)

}

func main() {
	if len(os.Args) < 2 {
		fmt.Printf("Usage: %s <outfile>\n", os.Args[0])
		os.Exit(1)
	}
	CreateFSAndDir(os.Args[1])
}
```

### manual

```
fdisk /dev/sda
    Command (m for help): n
    Partition type
      p   primary (0 primary, 0 extended, 4 free)
      e   extended (container for logical partitions)
    Select (default p): 

    Using default response p.
    Partition number (1-4, default 1): 
    First sector (2048-2097151, default 2048): 
    Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-2097151, default 2097151): 22527

    Created a new partition 1 of type 'Linux' and of size 10 MiB.

    Command (m for help): p
    Disk /dev/sda: 1 GiB, 1073741824 bytes, 2097152 sectors
    Disk model: Volume          
    Units: sectors of 1 * 512 = 512 bytes
    Sector size (logical/physical): 512 bytes / 512 bytes
    I/O size (minimum/optimal): 512 bytes / 512 bytes
    Disklabel type: dos
    Disk identifier: 0x4f95ea25

    Device     Boot Start   End Sectors Size Id Type
    /dev/sda1        2048 22527   20480  10M 83 Linux

    Command (m for help): w
    The partition table has been altered.
    Calling ioctl() to re-read partition table.
    Syncing disks.

mkfs.vfat -F 32 -s 2 /dev/sda1
fatlabel /dev/sda1 belgrave123
dd if=/dev/sda of=manual.img

```

**Comment by deitch** [comment]
Please use the attached gzip file [foo.img.gz](https://github.com/diskfs/go-diskfs/files/4128538/foo.img.gz), see what `blkid` gives you. It definitely has the right entry in place. The challenge I am up against is that the specs aren't clear on how to treat non 8.3 valid characters (e.g. lowercase or dashes) in the volume label. Technically, it is a directory entry, and should have those handled with the same protocol. However, the example you sent just puts the lower-case chars in the filename space.

I suspect it is the Linux tools misbehaving, but as long as the "correct" behaviour is readable, that would be fine.

**Comment by rmb938** [comment]
```
[root@fedora-s-4vcpu-8gb-sfo2-01 ~]# dd if=foo.img of=/dev/sda
20480+0 records in
20480+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0.883652 s, 11.9 MB/s
[root@fedora-s-4vcpu-8gb-sfo2-01 ~]# fdisk -lu /dev/sda
Disk /dev/sda: 2 GiB, 2147483648 bytes, 4194304 sectors
Disk model: Volume          
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start     End Sectors Size Id Type
/dev/sda1        2048 2099199 2097152   1G 83 Linux
[root@fedora-s-4vcpu-8gb-sfo2-01 ~]# blkid
/dev/vda1: UUID="b1438b9b-2cab-4065-a99a-08a96687f73c" TYPE="ext4" PARTUUID="7a0392d3-01"
/dev/sda1: LABEL_FATBOOT="config-2" UUID="4D35-EBF5" TYPE="vfat"
```

That image seems to have the same issue.

**Comment by deitch** [comment]
Yes. I dug deeper into how it does long names, I had forgotten that it actually overloads the flag, which made it not recognize it as a label, and actually think it is a file. Try this one.
[label.img.gz](https://github.com/diskfs/go-diskfs/files/4128640/label.img.gz)

**Comment by deitch** [comment]
My tests (pre-2.33) show that it works correctly: reads the label and doesn't think it is a file. Your tests (2.33+) should validate that.

**Comment by rmb938** [comment]
They don't...

```
[root@fedora-s-4vcpu-8gb-sfo2-01 ~]# dd if=label.img of=/dev/sda
20480+0 records in
20480+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 1.07649 s, 9.7 MB/s
[root@fedora-s-4vcpu-8gb-sfo2-01 ~]# fdisk -lu /dev/sda
Disk /dev/sda: 2 GiB, 2147483648 bytes, 4194304 sectors
Disk model: Volume          
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot Start     End Sectors Size Id Type
/dev/sda1        2048 2099199 2097152   1G 83 Linux
[root@fedora-s-4vcpu-8gb-sfo2-01 ~]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0    2G  0 disk 
└─sda1   8:1    0    1G  0 part 
vda    252:0    0  160G  0 disk 
└─vda1 252:1    0  160G  0 part /
[root@fedora-s-4vcpu-8gb-sfo2-01 ~]# blkid
/dev/vda1: UUID="b1438b9b-2cab-4065-a99a-08a96687f73c" TYPE="ext4" PARTUUID="7a0392d3-01"
/dev/sda1: LABEL_FATBOOT="config-2" UUID="D0F7-E6F7" TYPE="vfat"
```

Still doesn't have the label.

**Comment by deitch** [comment]
The only difference I can see is a cluster location. I will try that as well. Missing specs...

Can you give me access to your box again?

**Comment by deitch** [comment]
Here is one where the cluster refs are explicitly zeroed out.
[label.img.gz](https://github.com/diskfs/go-diskfs/files/4128687/label.img.gz)

**Comment by rmb938** [comment]
Yea sure. 157.245.183.113 I just about to head off to work so feel free to test whatever you need.

**Comment by deitch** [comment]
```
[root@fedora-s-4vcpu-8gb-sfo2-01 tmp]# dd if=label.img of=/dev/sda
20480+0 records in
20480+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 1.13797 s, 9.2 MB/s
[root@fedora-s-4vcpu-8gb-sfo2-01 tmp]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0    2G  0 disk
└─sda1   8:1    0    1G  0 part
vda    252:0    0  160G  0 disk
└─vda1 252:1    0  160G  0 part /
[root@fedora-s-4vcpu-8gb-sfo2-01 tmp]# blkid
/dev/vda1: UUID="b1438b9b-2cab-4065-a99a-08a96687f73c" TYPE="ext4" PARTUUID="7a0392d3-01"
/dev/sda1: LABEL_FATBOOT="config-2" LABEL="config-2" UUID="08BA-CFFB" TYPE="vfat"
```

Better!
