### ISSUE TITLE
Device size is zero when using blockdevice.

### ISSUE THREAD

**Issue by akhilerm** [diskfs/go-diskfs#52]
**What I did**
I tried to create a single GPT partition that spans the entire drive on a USB drive, using the below code.
```
func main() {
	diskPath := "/dev/sdb"
	disk, err := diskfs.Open(diskPath)
	if err != nil {
		fmt.Println("Error opening:", err)
	}
	endSector := (disk.Size / 512) - 34 // 34 is length of efi label
	t := &gpt.Table{
		Partitions: []*gpt.Partition{
			{
				Start: 2048,
				End:   uint64(endSector),
				Type:  gpt.LinuxFilesystem,
				},
		},
	}
	err = disk.Partition(t)
	if err != nil {
		fmt.Println("error partitioning : ", err)
	}
}
```

but the program exits with Error:
```
error partitioning :  Failed to write partition table: Error writing secondary partition array to disk: writeat /dev/sdb: negative offset
```

**What might be the problem:**
When the code was run in debug mode, found out that `devInfo` [here](https://github.com/diskfs/go-diskfs/blob/3bd1f70075f0eed12a5e50c1c38c39b94c755bd6/diskfs.go#L180) is having the size as zero.
When the call to create a partition is made  [here](https://github.com/diskfs/go-diskfs/blob/3bd1f70075f0eed12a5e50c1c38c39b94c755bd6/disk/disk.go#L63), the empty `d.Info.Size()` is passed causing the error to occur.

**Proposed solution:**
 replace `d.Info.Size()` with `d.Size` [here](https://github.com/diskfs/go-diskfs/blob/3bd1f70075f0eed12a5e50c1c38c39b94c755bd6/disk/disk.go#L63).
When this change was made `go-diskfs` worked as expected and the partition was created. 

**Additional Info**
- OS
```
akhil@MayaData:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Device on which I tried to create partition
```
akhil@MayaData:~$ udevadm info /dev/sdb
P: /devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/host2/target2:0:0/2:0:0:0/block/sdb
N: sdb
S: disk/by-id/usb-Kingston_DataTraveler_3.0_50E5495131BBB060892FBC8E-0:0
S: disk/by-path/pci-0000:00:14.0-usb-0:3:1.0-scsi-0:0:0:0
E: DEVLINKS=/dev/disk/by-id/usb-Kingston_DataTraveler_3.0_50E5495131BBB060892FBC8E-0:0 /dev/disk/by-path/pci-0000:00:14.0-usb-0:3:1.0-scsi-0:0:0:0
E: DEVNAME=/dev/sdb
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/host2/target2:0:0/2:0:0:0/block/sdb
E: DEVTYPE=disk
E: ID_BUS=usb
E: ID_DRIVE_THUMB=1
E: ID_INSTANCE=0:0
E: ID_MODEL=DataTraveler_3.0
E: ID_MODEL_ENC=DataTraveler\x203.0
E: ID_MODEL_ID=1666
E: ID_PATH=pci-0000:00:14.0-usb-0:3:1.0-scsi-0:0:0:0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_1_0-scsi-0_0_0_0
E: ID_REVISION=PMAP
E: ID_SERIAL=Kingston_DataTraveler_3.0_50E5495131BBB060892FBC8E-0:0
E: ID_SERIAL_SHORT=50E5495131BBB060892FBC8E
E: ID_TYPE=disk
E: ID_USB_DRIVER=usb-storage
E: ID_USB_INTERFACES=:080650:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Kingston
E: ID_VENDOR_ENC=Kingston
E: ID_VENDOR_ID=0951
E: MAJOR=8
E: MINOR=16
E: SUBSYSTEM=block
E: TAGS=:systemd:
E: USEC_INITIALIZED=159230551555
```
- Go version
```
akhil@MayaData:~$ go version
go version go1.13.1 linux/amd64
akhil@MayaData:~$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/akhil/.cache/go-build"
GOENV="/home/akhil/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/akhil/Work/Golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build076484881=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by deitch** [comment]
I _love_ it when someone opens a seriously good issue. Not, "this doesn't work", but "this doesn't work, here is precisely how I did it, and here is why I think it is." Thanks @akhilerm . Looking at it right now.

**Comment by deitch** [comment]
You are right on. The code [here](https://github.com/diskfs/go-diskfs/blob/3bd1f70075f0eed12a5e50c1c38c39b94c755bd6/diskfs.go#L192-L205), a few lines below the area that you highlighted, was created _specifically_ because the  call to `devInfo.Size()`returns 0 for block devices (as opposed to files). Why it was not taken advantage of [here](https://github.com/diskfs/go-diskfs/blob/3bd1f70075f0eed12a5e50c1c38c39b94c755bd6/disk/disk.go#L63), as you highlighted, must simply be an oversight.

PR coming shortly. I will flag you on it, and ask if you can confirm the commit works before we merge it in.

**Comment by deitch** [comment]
@akhilerm see #53, and please confirm that your use case also passes. We can then merge it in.

**Comment by akhilerm** [comment]
Yep @deitch It works. Thanks for the quick turn around.
