### ISSUE TITLE
create tagged releases for go-diskfs

### ISSUE THREAD

**Issue by akhilerm** [diskfs/go-diskfs#58]
As of now, to include go-diskfs as a dependency we need to refer to a specific commit in either `Gopkg.toml` or `go.mod` file.

Creating versioned release with semantic versioning `v1.0.x` will help to give a clean dependency in the `Gopkg.toml` or `go.mod` file.

**Comment by deitch** [comment]
Done. We will start using tags with minor versions for new features and adding new filesystems, patches for bug fixes.
