### ISSUE TITLE
undefined: unix.IoctlGetInt

### ISSUE THREAD

**Issue by tvories** [diskfs/go-diskfs#75]
I'm getting an error when trying to import this library in my go code.

```
# github.com/diskfs/go-diskfs
..\..\go\src\github.com\diskfs\go-diskfs\diskfs.go:313:28: undefined: unix.IoctlGetInt
..\..\go\src\github.com\diskfs\go-diskfs\diskfs.go:317:29: undefined: unix.IoctlGetInt
```

I am very new to go, so I could definitely be doing something wrong, but this is the first issue I've had with an import.

This is on a Windows 10 machine.  I haven't tried yet with another OS.

**Comment by deitch** [comment]
Good catch. I haven't actually built this on windows before, and this is (I think) the only place it will run into trouble.

> I am very new to go, so I could definitely be doing something wrong, but this is the first issue I've had with an import.

You aren't doing anything wrong, just stumbling across an issue here.

In go, if you have a file whose source only works on a particular platform, you create it with `<filename>_<platform>.go`. The concrete example here is [here](https://github.com/diskfs/go-diskfs/tree/master/disk), where you will see 3 files:

```
disk.go
disk_test.go
disk_unix.go
disk_windows.go
```

Where `disk.go` is generic, `disk_unix.go` is for all unix and unix-like platforms, and `disk_windows.go` is for windows (`disk_test.go` is for testing, but that is a different question entirely).

We should have the same thing here for `diskfs.go`, where we tease it out per platform.

FWIW, if you ran this under Windows Services for Linux (WSL2), it probably would work. But we want it working across all. I am going to open a PR for this shortly. Nice catch!

**Comment by deitch** [comment]
I just opened #76 which should fix this (as soon as CI is green, will merge in). You will get an error if you try to work directly with a block device in Windows, but everything else will work. Since I don't know quite yet how to read block device info in Windows, it will have to do for now.

If you know and want to help, please.

**Comment by deitch** [comment]
All good. Try it now.

**Comment by tvories** [comment]
Thanks for the crazy fast response!  I had just tried this on my mac this morning before I saw your fix and I didn't have this issue.  I'll give it a shot now on my Windows system.

**Comment by tvories** [comment]
OK, so I am pretty sure I cleared out the old mod and re-ran `go get`

I am getting a new error with some of the old.  Looks like it's still evaluating `diskfs_unix` even though it's running on windows

```
# github.com/diskfs/go-diskfs
..\..\go\src\github.com\diskfs\go-diskfs\diskfs_unix.go:17:28: undefined: unix.IoctlGetInt
..\..\go\src\github.com\diskfs\go-diskfs\diskfs_unix.go:21:29: undefined: unix.IoctlGetInt
..\..\go\src\github.com\diskfs\go-diskfs\diskfs_windows.go:8:6: getSectorSizes redeclared in this block
        previous declaration at ..\..\go\src\github.com\diskfs\go-diskfs\diskfs_unix.go:11:48
..\..\go\src\github.com\diskfs\go-diskfs\diskfs_windows.go:8:24: undefined: os
```

**Comment by deitch** [comment]
Try `go get github.com/diskfs/go-diskfs@master` to force the latest?

**Comment by tvories** [comment]
I added a go mod to my directory and specified @master 

here are my current error results:

![image](https://user-images.githubusercontent.com/13934524/100655755-f2ba9080-3308-11eb-8d5a-44a793a08231.png)

**Comment by deitch** [comment]
Oh that is my fault. I forgot the build annotation. `<file>_<platform>.go` works, but `<file>_unix.go` does not, because `unix` is not an actual platform. I need to add the build annotation.

Thanks for catching, PR coming very shortly.

**Comment by tvories** [comment]
Fixed!  Thanks again!

**Comment by xaduha** [comment]
@deitch Seems like squashfs broke windows builds again, from 2f50f30 and upwards `GOOS=windows go build` fails. It's not in CI? In any case the latest tag is v1.1.1, so it's unaffected.

**Comment by deitch** [comment]
> It's not in CI?

That isn't a bad idea. Feel free to open a PR to add it to the matrix.

**Comment by deitch** [comment]
Try now with #96
