### ISSUE TITLE
Bootable iso example

### ISSUE THREAD

**Issue by carbonin** [diskfs/go-diskfs#80]
I'm trying to create a bootable iso. The gist of it, is I want to recreate this command:
```
genisoimage \
   -V my-volume \
   -c isolinux/boot.cat \
   -b isolinux/isolinux.bin \
   -no-emul-boot \
   -boot-load-size 4 \
   -boot-info-table \
   -eltorito-alt-boot \
   -e images/efiboot.img \
   -no-emul-boot \
   -o test-iso.iso \
   /tmp/iso-test/
```

I think the issue is in my finalize options which currently look like this:
```
options := iso9660.FinalizeOptions{
        VolumeIdentifier: "my-volume",
        RockRidge:        true,
        ElTorito: &iso9660.ElTorito{
                BootCatalog: "isolinux/boot.cat",
                Entries: []*iso9660.ElToritoEntry{
                        &iso9660.ElToritoEntry{
                                Platform:    iso9660.BIOS,
                                Emulation:   iso9660.NoEmulation,
                                BootFile:    "isolinux/isolinux.bin",
                                LoadSegment: 4,
                        },      
                        &iso9660.ElToritoEntry{
                                Platform:  iso9660.EFI,
                                Emulation: iso9660.NoEmulation,
                                BootFile:  "images/efiboot.img",
                        },      
                },
        },        
}
```

After running my code I get an iso that `file` shows as bootable but doesn't actually boot in a VM:
![image](https://user-images.githubusercontent.com/12697904/101661581-76196780-3a16-11eb-9cb6-7a0b79dd79a0.png)

`isoinfo -i test-iso.iso -d` shows:
```
    Eltorito validation header:
    Hid 1
    Arch 0 (x86)
    ID 'https://github.com/disk'
    Key 55 AA
    Eltorito defaultboot header:
        Bootid 88 (bootable)
        Boot media 0 (No Emulation Boot)
        Load segment 4
        Sys type 0
        Nsect 4C
        Bootoff 0 0
```
Any hints?

**Comment by carbonin** [comment]
Also, I would be happy to add an example ... once I get this working :sweat_smile:

**Comment by deitch** [comment]
I assume the `isoinfo` output from above is from the one generated via this library. What does the output of an iso generated using `genisoimage` look like?

**Comment by deitch** [comment]
> Also, I would be happy to add an example ... once I get this working 😅

And very happy to take it! 😁

**Comment by deitch** [comment]
Also, what do you get when running the actual bootable image? What is in `/tmp/iso-test/`?

**Comment by carbonin** [comment]
Here's the whole output for the image from this library for reference:
```
CD-ROM is in ISO 9660 format
System id: 
Volume id: my-volume
Volume set id: 
Publisher id: 
Data preparer id: https://github.com/diskfs/go-diskfs
Application id: 
Copyright File id: 
Abstract File id: 
Bibliographic File id: 
Volume set size is: 1
Volume set sequence number is: 1
Logical block size is: 2048
Volume size is: 224690
El Torito VD version 1 found, boot catalog is in sector 29
NO Joliet present
Rock Ridge signatures version 1 found
Eltorito validation header:
    Hid 1
    Arch 0 (x86)
    ID 'https://github.com/disk'
    Key 55 AA
    Eltorito defaultboot header:
        Bootid 88 (bootable)
        Boot media 0 (No Emulation Boot)
        Load segment 4
        Sys type 0
        Nsect 4C
        Bootoff 0 0
```

> What does the output of an iso generated using genisoimage look like?

```
CD-ROM is in ISO 9660 format
System id: LINUX
Volume id: my-image
Volume set id: 
Publisher id: 
Data preparer id: 
Application id: GENISOIMAGE ISO 9660/HFS FILESYSTEM CREATOR (C) 1993 E.YOUNGDALE (C) 1997-2006 J.PEARSON/J.SCHILLING (C) 2006-2007 CDRKIT TEAM
Copyright File id: 
Abstract File id: 
Bibliographic File id: 
Volume set size is: 1
Volume set sequence number is: 1
Logical block size is: 2048
Volume size is: 224840
El Torito VD version 1 found, boot catalog is in sector 30
NO Joliet present
NO Rock Ridge present
Eltorito validation header:
    Hid 1
    Arch 0 (x86)
    ID ''
    Key 55 AA
    Eltorito defaultboot header:
        Bootid 88 (bootable)
        Boot media 0 (No Emulation Boot)
        Load segment 0
        Sys type 0
        Nsect 4
        Bootoff 1F 31
```

> Also, what do you get when running the actual bootable image?

A live OS

> What is in /tmp/iso-test/?

```
$ tree /tmp/iso-test/
/tmp/iso-test/
├── EFI
│   └── redhat
│       └── grub.cfg
├── images
│   ├── efiboot.img
│   ├── ignition.img
│   ├── my_image.img
│   └── pxeboot
│       ├── initrd.img
│       ├── rootfs.img
│       └── vmlinuz
├── isolinux
│   ├── boot.cat
│   ├── boot.msg
│   ├── isolinux.bin
│   ├── isolinux.cfg
│   ├── ldlinux.c32
│   ├── libcom32.c32
│   ├── libutil.c32
│   └── vesamenu.c32
└── zipl.prm

5 directories, 16 files
```

**Comment by deitch** [comment]
There isn't a _lot_ of difference between the two, but a few: number of sectors, total size, boot offset, a few.

I would like to try and recreate all of this. As far as I can tell, your isolinux dir is standard. Where is the rest of the directory from? And can you share the entire go program that includes the above? Obviously sanitized if needed. I can recreate it easily, but I might not do _exactly_ what you do.

Heads up, going to be a few days.

**Comment by carbonin** [comment]
Sure, let me clean it up and see if I can publish something.

**Comment by carbonin** [comment]
Just went and made a repo https://github.com/carbonin/iso-edit

**Comment by deitch** [comment]
Great! I will get to it. Hopefully, it is just a documentation issue, but if it is a real bug, then I will be glad we found it.

It will take a few days; in any case, sitting there looking at hex structures in xxd takes time.

**Comment by carbonin** [comment]
Fantastic, much appreciated!

**Comment by carbonin** [comment]
So I'm not sure if this is contributing to the problem, but I also found that the files extracted are significantly different sizes than the ones I can see when mounting the iso...

Mounted:
```
14:00:43:~/Source/iso-edit/isos/rhcos$ ls -lR
.:
total 7
dr-xr-xr-x. 3 root root 2048 Oct  9 14:01 EFI
dr-xr-xr-x. 3 root root 2048 Oct  9 14:01 images
dr-xr-xr-x. 2 root root 2048 Oct  9 14:01 isolinux
-r--r--r--. 1 root root  132 Oct  9 13:18 zipl.prm

./EFI:
total 2
dr-xr-xr-x. 2 root root 2048 Oct  9 14:01 redhat

./EFI/redhat:
total 2
-r--r--r--. 1 root root 1061 Oct  9 13:18 grub.cfg

./images:
total 8240
-r--r--r--. 1 root root 8173158 Oct  9 14:01 efiboot.img
-r--r--r--. 1 root root  262144 Oct  9 13:52 ignition.img
dr-xr-xr-x. 2 root root    2048 Oct  9 14:01 pxeboot

./images/pxeboot:
total 887826
-r--r--r--. 1 root root  80239428 Oct  9 14:01 initrd.img
-r--r--r--. 1 root root 819969024 Oct  9 14:01 rootfs.img
-r--r--r--. 1 root root   8924528 Oct  9 13:52 vmlinuz

./isolinux:
total 383
-r--r--r--. 1 root root   2048 Oct  9 14:01 boot.cat
-r--r--r--. 1 root root     58 Oct  9 13:18 boot.msg
-r-xr-xr-x. 1 root root  38912 Oct  9 14:01 isolinux.bin
-r--r--r--. 1 root root   2047 Oct  9 13:18 isolinux.cfg
-r-xr-xr-x. 1 root root 116320 Oct  9 14:01 ldlinux.c32
-r-xr-xr-x. 1 root root 180476 Oct  9 14:01 libcom32.c32
-r-xr-xr-x. 1 root root  23924 Oct  9 14:01 libutil.c32
-r-xr-xr-x. 1 root root  26724 Oct  9 14:01 vesamenu.c32
```

Extracted (using the code in https://github.com/carbonin/iso-edit):
```
13:59:58:/tmp$ ls -lR iso-test
iso-test:
total 4
drwxr-xr-x. 3 ncarboni ncarboni  60 Dec 10 13:59 EFI
drwxr-xr-x. 3 ncarboni ncarboni 120 Dec 10 13:59 images
drwxr-xr-x. 2 ncarboni ncarboni 200 Dec 10 13:59 isolinux
-rw-rw-r--. 1 ncarboni ncarboni 132 Dec 10 13:59 zipl.prm

iso-test/EFI:
total 0
drwxr-xr-x. 2 ncarboni ncarboni 60 Dec 10 13:59 redhat

iso-test/EFI/redhat:
total 4
-rw-rw-r--. 1 ncarboni ncarboni 1082 Dec 10 13:59 grub.cfg

iso-test/images:
total 4196
-rw-rw-r--. 1 ncarboni ncarboni 4128768 Dec 10 13:59 efiboot.img
-rw-rw-r--. 1 ncarboni ncarboni  163840 Dec 10 13:59 ignition.img
-rw-rw-r--. 1 ncarboni ncarboni    1056 Dec 10 13:59 my_image.img
drwxr-xr-x. 2 ncarboni ncarboni     100 Dec 10 13:59 pxeboot

iso-test/images/pxeboot:
total 444000
-rw-rw-r--. 1 ncarboni ncarboni  40140800 Dec 10 13:59 initrd.img
-rw-rw-r--. 1 ncarboni ncarboni 410025984 Dec 10 13:59 rootfs.img
-rw-rw-r--. 1 ncarboni ncarboni   4489216 Dec 10 13:59 vmlinuz

iso-test/isolinux:
total 328
-rw-rw-r--. 1 ncarboni ncarboni   2048 Dec 10 13:59 boot.cat
-rw-rw-r--. 1 ncarboni ncarboni     58 Dec 10 13:59 boot.msg
-rw-rw-r--. 1 ncarboni ncarboni  38912 Dec 10 13:59 isolinux.bin
-rw-rw-r--. 1 ncarboni ncarboni   2068 Dec 10 13:59 isolinux.cfg
-rw-rw-r--. 1 ncarboni ncarboni  98304 Dec 10 13:59 ldlinux.c32
-rw-rw-r--. 1 ncarboni ncarboni 131072 Dec 10 13:59 libcom32.c32
-rw-rw-r--. 1 ncarboni ncarboni  23924 Dec 10 13:59 libutil.c32
-rw-rw-r--. 1 ncarboni ncarboni  26724 Dec 10 13:59 vesamenu.c32
```

**Comment by carbonin** [comment]
Created a separate branch to try to track down the size issue.
https://github.com/carbonin/iso-edit/tree/extract_test

This clearly shows that the size reported by `ReadDir` is different from what is written.
@deitch should I open a separate bug for this? It might be related to the boot issue, but it might not also...

**Comment by carbonin** [comment]
Opened a PR to fix the file size bug https://github.com/diskfs/go-diskfs/pull/81

Will update if it fixes my entire use case

**Comment by carbonin** [comment]
It seems that #81 does not solve the boot problem I was experiencing originally.

**Comment by deitch** [comment]
@carbonin trying to get your `genisoimage` command to work. Which `efiboot.img` are you using? The rest doesn't matter much, as it isn't used in your `genisoimage` command, but the `efiboot.img` is needed (and isn't referenced in your [linked repo](https://github.com/carbonin/iso-edit)). We need to recreate this precisely.

**Comment by carbonin** [comment]
It's from this iso https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.1/rhcos-4.6.1-x86_64-live.x86_64.iso

My use case is extracting that iso, making some edits, and repacking it.

**Comment by carbonin** [comment]
Also, did you get a chance to take a look at https://github.com/diskfs/go-diskfs/pull/81?

**Comment by deitch** [comment]
Managed to get a much simpler version to recreate the issue.

https://github.com/diskfs/isotester

**Comment by deitch** [comment]
Well, this has been entertaining. Took long enough to dig back into it, but there are two pieces missing. The irony is, I am _positive_ I remember working with these when iso9660 was implemented. Which goes to show how much one must trust their memory.

* the boot catalog is not being inserted properly into the filesystem. There are tests for it, so something is missing.
* the boot file is not being modified to create the boot information table

**Comment by deitch** [comment]
No, it is even stranger. The boot catalog _is_ being inserted. My Mac won't see it on mounting, but I can see it when inspecting the directory entry looking at the iso in hex.

**Comment by deitch** [comment]
Phew, got it. It looks like the boot catalog file is added _after_ the directory size has been calculated. So the directory entry for the parent of wherever the boot catalog goes has a size that stops just short of the actually catalog entry.

**Comment by deitch** [comment]
This should not be closed yet.

**Comment by deitch** [comment]
@carbonin can you take another look with the latest? I don't think it is a full fix, but we should see improvement.

**Comment by carbonin** [comment]
Sure, but I think #81 is also very important. Do you want me to open a separate issue for that?

**Comment by deitch** [comment]
No need to open a separate issue with #81 in place.

**Comment by carbonin** [comment]
After the latest change the boot offset is set (according to isoinfo) but it still doesn't boot.
```
$ isoinfo -d -i my-rhcos.iso 
CD-ROM is in ISO 9660 format
System id: 
Volume id: rhcos-46.82.202010091720-0
Volume set id: 
Publisher id: 
Data preparer id: https://github.com/diskfs/go-diskfs
Application id: 
Copyright File id: 
Abstract File id: 
Bibliographic File id: 
Volume set size is: 1
Volume set sequence number is: 1
Logical block size is: 2048
Volume size is: 448259
El Torito VD version 1 found, boot catalog is in sector 27
NO Joliet present
NO Rock Ridge present
Eltorito validation header:
    Hid 1
    Arch 0 (x86)
    ID 'https://github.com/disk'
    Key 55 AA
    Eltorito defaultboot header:
        Bootid 88 (bootable)
        Boot media 0 (No Emulation Boot)
        Load segment 4
        Sys type 0
        Nsect 4C
        Bootoff 6D642 448066
```

![image](https://user-images.githubusercontent.com/12697904/102363654-9bacf080-3f83-11eb-8c49-1bd6e51ab20f.png)

**Comment by deitch** [comment]
@carbonin I found an error in the example:

```go
                        &iso9660.ElToritoEntry{
                                Platform:    iso9660.BIOS,
                                Emulation:   iso9660.NoEmulation,
                                BootFile:    "isolinux/isolinux.bin",
                                LoadSegment: 4,
                        },      
```

Why are you setting the `LoadSegment` to 4? This causes the boot catalog to have an entry that says to load segment 4 from the boot file, see https://pdos.csail.mit.edu/6.828/2014/readings/boot-cdrom.pdf , page 10. 

Removing this doesn't solve it completely, but a step forward.

See the latest update at https://github.com/diskfs/isotester

**Comment by carbonin** [comment]
> Why are you setting the LoadSegment to 4?

No idea :sweat_smile: I thought that was the equivalent of the genisoimage arg `-boot-load-size 4`

**Comment by deitch** [comment]
Ah no. That is which segment to load, not how many sectors to load. Something I wrong with that too, still figuring it out.

**Comment by deitch** [comment]
One more #83 adds it, and I updated the example at https://github.com/diskfs/isotester along with the documentation.

We still have a checksum issue, but a big improvement. Please try it.

**Comment by carbonin** [comment]
> We still have a checksum issue, but a big improvement. Please try it.

yup seems about right

![image](https://user-images.githubusercontent.com/12697904/102394257-7b8f2880-3fa7-11eb-9bb5-581bffc5353f.png)

**Comment by deitch** [comment]
I know what it is, too. :-)

**Comment by deitch** [comment]
@carbonin I think it finally got it. Take a gander at the latest. If that is clean, we can close this, and maybe cut a new patch release.

**Comment by carbonin** [comment]
Just did a quick test and it seems to work! Thanks for all the work @deitch 

The only other thing I think I'll need to do is also run `isohybrid` on the resulting image, but that's likely a separate issue.
