### ISSUE TITLE
Function for isoinfo-like data

### ISSUE THREAD

**Issue by carbonin** [diskfs/go-diskfs#92]
Is there a way to use this library to get data similar to what is given by `isoinfo -lR -i test.iso`?

Sample output:
```
Directory listing of /
dr-xr-xr-x   5    0    0            2048 Oct  9 2020 [     29 02]  . 
dr-xr-xr-x   5    0    0            2048 Oct  9 2020 [     29 02]  .. 
dr-xr-xr-x   3    0    0            2048 Oct  9 2020 [     33 02]  EFI 
dr-xr-xr-x   3    0    0            2048 Oct  9 2020 [     30 02]  images 
dr-xr-xr-x   2    0    0            2048 Oct  9 2020 [     32 02]  isolinux 
-r--r--r--   1    0    0             132 Oct  9 2020 [   4053 00]  zipl.prm 
...
Directory listing of /images/pxeboot/
dr-xr-xr-x   2    0    0            2048 Oct  9 2020 [     31 02]  . 
dr-xr-xr-x   3    0    0            2048 Oct  9 2020 [     30 02]  .. 
-r--r--r--   1    0    0        80239428 Oct  9 2020 [   4182 00]  initrd.img 
-r--r--r--   1    0    0       819969024 Oct  9 2020 [  43362 00]  rootfs.img 
-r--r--r--   1    0    0         8924528 Oct  9 2020 [ 443738 00]  vmlinuz 
```

Specifically I'm looking to get the file size and offset without first unpacking the image.

**Comment by deitch** [comment]
The data is there. What is missing from your ability to do it? The [filesystem read example](https://github.com/diskfs/go-diskfs/blob/master/examples/filesystem_read.go) does a [ReadDir](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.1.1/filesystem#FileSystem) which returns an [os.FileInfo](https://pkg.go.dev/os#FileInfo) for each file. Is that not sufficient?

**Comment by carbonin** [comment]
I'm specifically looking for the file's offset into the iso which isn't present in the file info.

**Comment by carbonin** [comment]
More a property of the file as a part of the iso rather than the file if I were to extract it, if that makes sense.

**Comment by deitch** [comment]
Ah, I see.

That wouldn't be in the usual file/dir-level API, you would need something lower.

Part of it is there, you can look at how `GetFilesystem` is implemented, which really just calls [iso9660.Read](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.1.1/filesystem/iso9660#Read), which returns a [iso96600.Filesystem](https://pkg.go.dev/github.com/diskfs/go-diskfs@v1.1.1/filesystem/iso9660#FileSystem), which, in turn, gives you the same `ReadDir` you saw above.

So getting an actual `iso9660.FileSystem` structure can be done either by `GetFilesystem` and than casting, or by calling the `iso9660.Read` directly. 

The missing part is getting information about each file's on-disk location. Fortunately, the routines that walk the tree, primarily [readDirectory](https://github.com/diskfs/go-diskfs/blob/29b62ddcc13e0d45cf3ce57e586585b0998bcac1/filesystem/iso9660/iso9660.go#L399) already return a [directoryEntry](https://github.com/diskfs/go-diskfs/blob/29b62ddcc13e0d45cf3ce57e586585b0998bcac1/filesystem/iso9660/directoryentry.go#L26-L43), which has that data. We just [copy only the essentials over to []os.FileInfo](https://github.com/diskfs/go-diskfs/blob/29b62ddcc13e0d45cf3ce57e586585b0998bcac1/filesystem/iso9660/iso9660.go#L313-L324) before returning it.

So you could open a PR to create another func just on `iso9660.FileSystem`, say `ReadDirDetails` or similar, that returns `iso9660.FileInfo`. Then you are good to go.

**Comment by carbonin** [comment]
Turns out all I needed for this was to expose the directory entry location info.
I just added a method on iso9660.File for that in https://github.com/diskfs/go-diskfs/pull/94
