### ISSUE TITLE
Making two partitions in one table

### ISSUE THREAD

**Issue by xaduha** [diskfs/go-diskfs#95]
Haven't found any instances of two partitions being made anywhere, is it supported? No matter what I do first partition just takes the rest of the disk.

(btw there's a typo in the filename, `gpt/partiton.go`)

**Comment by deitch** [comment]
> (btw there's a typo in the filename, gpt/partiton.go)

Yes, quite, and it has been there a long time. It just never was worth fixing it.

**Comment by deitch** [comment]
> Haven't found any instances of two partitions being made anywhere, is it supported? No matter what I do first partition just takes the rest of the disk.

Sure, why not? How are you making the one partition? Post some samples and let's see.

**Comment by xaduha** [comment]
Sorry, nevermind, I just was using wrong tools to look at the image produced. `cfdisk` and `fdisk -l` doesn't seem to like it and when copied to USB stick Windows 10 doesn't seem to like what it sees either. But `gdisk -l` and `cgdisk` have no problem with it.

**Comment by deitch** [comment]
No problem. I am glad it is working. 😄
